language: php

php:
    - '5.6'
    - '7.0'
    - nightly
    - hhvm

before_script: composer install

script: phpunit --bootstrap vendor/autoload.php tests

matrix:
    fast-finish: true
    allow_failures:
        - php: nightly
        - php: hhvm
