language: php

php:
    - '7.0'
    - '7.1'
    - nightly
    - hhvm

before_script: composer install --ignore-platform-reqs

script: ./test.sh

matrix:
    fast-finish: true
    allow_failures:
        - php: nightly
        - php: hhvm
